### ISSUE TITLE
Error during installing, llvm 3.5, OS X

### ISSUE THREAD

**Issue by tiye** [guangwong/node-llvm-x#3]
``` text
➤➤ llc --version
LLVM (http://llvm.org/):
  LLVM version 3.5.1
  Optimized build with assertions.
  Built Jan 15 2015 (18:24:46).
  Default target: x86_64-apple-darwin14.3.0
  Host CPU: core-avx2

  Registered Targets:
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
➤➤ node -v
v0.12.0

➤➤ npm i --save llvm-x
npm WARN package.json sepal@0.0.1 No repository field.
npm WARN package.json sepal@0.0.1 No README data
-
> ref@0.1.3 install /Users/chen/repo/cirru/sepal/node_modules/llvm-x/node_modules/ref
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cc:45:29: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> Address(const Arguments& args) {
                            ^~~~~~~~~
                            v8::internal::Arguments
/Users/chen/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:46:15: error: calling a protected constructor of class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/chen/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/binding.cc:48:26: error: type 'const v8::internal::Arguments' does not provide a subscript operator
  Local<Value> buf = args[0];
                     ~~~~^~
../src/binding.cc:51:19: error: no member named 'New' in 'v8::String'
          String::New("address: Buffer instance expected")));
          ~~~~~~~~^
../src/binding.cc:54:24: error: type 'const v8::internal::Arguments' does not provide a subscript operator
  int64_t offset = args[1]->IntegerValue();
                   ~~~~^~
../src/binding.cc:57:62: error: too few arguments to function call, expected 2, have 1
  Local<Number> ret = Number::New(static_cast<double>(intptr));
                      ~~~~~~~~~~~                            ^
/Users/chen/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:3: note: 'New' declared here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../src/binding.cc:59:16: error: no member named 'Close' in 'v8::HandleScope'
  return scope.Close(ret);
         ~~~~~ ^
../src/binding.cc:69:28: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
Handle<Value> IsNull(const Arguments& args) {
                           ^~~~~~~~~
                           v8::internal::Arguments
/Users/chen/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:70:15: error: calling a protected constructor of class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/chen/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
 operatornding.cc:72:26: error: type 'const v8::internal::Arguments' does not provide a subscript|
  Local<Value> buf = args[0];
                     ~~~~^~
../src/binding.cc:75:19: error: no member named 'New' in 'v8::String'
          String::New("isNull: Buffer instance expected")));
          ~~~~~~~~^
../src/binding.cc:78:24: error: type 'const v8::internal::Arguments' does not provide a subscript operator
  int64_t offset = args[1]->IntegerValue();
                   ~~~~^~
../src/binding.cc:80:47: error: too few arguments to function call, expected 2, have 1
  Handle<Value> ret = Boolean::New(ptr == NULL);
                      ~~~~~~~~~~~~            ^
/Users/chen/.node-gyp/0.12.0/deps/v8/include/v8.h:6194:1: note: 'New' declared here
Handle<Boolean> Boolean::New(Isolate* isolate, bool value) {
^
../src/binding.cc:82:16: error: no member named 'Close' in 'v8::HandleScope'
  return scope.Close(ret);
         ~~~~~ ^
../src/binding.cc:94:19: error: no member named 'New' in 'v8::String'
    rtn = String::New("BE");
          ~~~~~~~~^
../src/binding.cc:96:19: error: no member named 'New' in 'v8::String'
    rtn = String::New("LE");
          ~~~~~~~~^
../src/binding.cc:121:3: error: unexpected namespace name 'Buffer': expected expression
  Buffer *buf = Buffer::New(ptr, buf_size, unref_null_cb, user_data);
  ^
../src/binding.cc:121:11: error: use of undeclared identifier 'buf'
  Buffer *buf = Buffer::New(ptr, buf_size, unref_null_cb, user_data);
          ^
../src/binding.cc:122:45: error: 'New' is a private member of 'v8::PersistentBase<v8::Object>'
  null_pointer_buffer = Persistent<Object>::New(buf->handle_);
                                            ^
/Users/chen/.node-gyp/0.12.0/deps/v8/include/v8.h:572:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/chen/repo/cirru/sepal/node_modules/llvm-x/node_modules/ref
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
\
> ref@1.0.1 install /Users/chen/repo/cirru/sepal/node_modules/llvm-x/node_modules/ffi/node_modules/ref-struct/node_modules/ref
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/binding.node
  SOLINK_MODULE(target) Release/binding.node: Finished

> ffi@1.2.7 install /Users/chen/repo/cirru/sepal/node_modules/llvm-x/node_modules/ffi
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
  LIBTOOL-STATIC Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
In file included from ../src/ffi.cc:2:
../src/ffi.h:57:43: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> FFIPrepCif(const Arguments& args);
                                          ^~~~~~~~~
                                          v8::internal::Arguments
/Users/chen/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ffi.cc:2:
../src/ffi.h:58:46: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> FFIPrepCifVar(const Arguments& args);
                                             ^~~~~~~~~
                                             v8::internal::Arguments
/Users/chen/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ffi.cc:2:
../src/ffi.h:59:40: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> FFICall(const Arguments& args);
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/chen/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ffi.cc:2:
../src/ffi.h:60:45: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> FFICallAsync(const Arguments& args);
                                            ^~~~~~~~~
                                            v8::internal::Arguments
/Users/chen/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ffi.cc:2:
../src/ffi.h:64:40: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> Strtoul(const Arguments& args);
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/chen/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ffi.cc:2:
../src/ffi.h:94:41: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> Callback(const Arguments& args);
                                        ^~~~~~~~~
                                        v8::internal::Arguments
/Users/chen/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/ffi.cc:19:15: error: calling a protected constructor of class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/chen/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/ffi.cc:21:3: error: unexpected namespace name 'Buffer': expected expression
  Buffer *buf = Buffer::New(ptr, length, wrap_pointer_cb, user_data);
  ^
../src/ffi.cc:21:11: error: use of undeclared identifier 'buf'
  Buffer *buf = Buffer::New(ptr, length, wrap_pointer_cb, user_data);
          ^
../src/ffi.cc:22:16: error: no member named 'Close' in 'v8::HandleScope'
  return scope.Close(buf->handle_);
         ~~~~~ ^
../src/ffi.cc:22:22: error: use of undeclared identifier 'buf'
  return scope.Close(buf->handle_);
                     ^
../src/ffi.cc:28:33: error: too few arguments to function call, single argument 'isolate' was not specified
  Local<Object> o = Object::New();
                    ~~~~~~~~~~~ ^
/Users/chen/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:3: note: 'New' declared here
  static Local<Object> New(Isolate* isolate);
  ^
../src/ffi.cc:31:18: error: no member named 'NewSymbol' in 'v8::String'
  o->Set(String::NewSymbol("dlopen"),  WrapPointer((char *)dlopen));
         ~~~~~~~~^
../src/ffi.cc:32:18: error: no member named 'NewSymbol' in 'v8::String'
  o->Set(String::NewSymbol("dlclose"), WrapPointer((char *)dlclose));
         ~~~~~~~~^
../src/ffi.cc:33:18: error: no member named 'NewSymbol' in 'v8::String'
  o->Set(String::NewSymbol("dlsym"),   WrapPointer((char *)dlsym));
         ~~~~~~~~^
../src/ffi.cc:34:18: error: no member named 'NewSymbol' in 'v8::String'
  o->Set(String::NewSymbol("dlerror"), WrapPointer((char *)dlerror));
         ~~~~~~~~^
../src/ffi.cc:36:23: error: no member named 'NewSymbol' in 'v8::String'
  target->Set(String::NewSymbol("StaticFunctions"), o);
              ~~~~~~~~^
../src/ffi.cc:49:3: error: no matching function for call to 'NODE_SET_METHOD'
  NODE_SET_METHOD(target, "ffi_prep_cif", FFIPrepCif);
  ^~~~~~~~~~~~~~~
/Users/chen/.node-gyp/0.12.0/src/node.h:240:25: note: expanded from macro 'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/chen/.node-gyp/0.12.0/src/node.h:228:13: note: candidate function [with TypeName = v8::Handle<v8::Object>] not viable: no known conversion from
      'Handle<v8::Value> (const v8::internal::Arguments &)' to 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
../src/ffi.cc:50:3: error: no matching function for call to 'NODE_SET_METHOD'
  NODE_SET_METHOD(target, "ffi_prep_cif_var", FFIPrepCifVar);
  ^~~~~~~~~~~~~~~
/Users/chen/.node-gyp/0.12.0/src/node.h:240:25: note: expanded from macro 'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/chen/.node-gyp/0.12.0/src/node.h:228:13: note: candidate function [with TypeName = v8::Handle<v8::Object>] not viable: no known conversion from
      'Handle<v8::Value> (const v8::internal::Arguments &)' to 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/chen/repo/cirru/sepal/node_modules/llvm-x/node_modules/ffi
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "--save" "llvm-x"
npm ERR! node v0.12.0
npm ERR! npm  v2.1.6
npm ERR! code ELIFECYCLE

npm ERR! ref@0.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@0.1.3 install script.
npm ERR! This is most likely a problem with the ref package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ref
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chen/repo/cirru/sepal/npm-debug.log
```

**Comment by guangwong** [comment]
你先用 llvm 3.4 试试。。 。。

**Comment by tiye** [comment]
`brew install llvm34` 也试过, 好像也是这种错误, 没留 log...
这个错能看出来是错在什么上边吗?

**Comment by guangwong** [comment]
我这周看看，解决下， 新版的 Mac 系统好像有问题。。 我原来是在 linux 上用的。。
